# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/opensource-nepal/commitlint
    rev: v1.3.0
    hooks:
    -   id: commitlint
# See https://pre-commit.com/hooks.html for more hooks
-   repo: https://github.com/astral-sh/ruff-pre-commit
# Ruff version.
    rev: v0.7.0
    hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [--fix, --ignore, E501]

    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
